apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ip-pool
  namespace: metallb-system
spec:
  addresses:
    # https://metallb.io/configuration/#layer-2-configuration
    # - 10.0.50.64/28
    # - 172.19.216.44/20
    - 192.168.1.100-192.168.1.105
